// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizService.Api.Data;

#nullable disable

namespace QuizService.Api.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20260820040806_AddPracticeSets")]
    partial class AddPracticeSets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("quiz")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizService.Api.Entities.EssayQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chapter")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPublishedForPractice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("SourceMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Manual");

                    b.Property<string>("SuggestedAnswer")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("Chapter");

                    b.ToTable("essay_questions", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.EssayQuestionLopVisibility", b =>
                {
                    b.Property<Guid>("EssayQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EssayQuestionId", "LopId");

                    b.HasIndex("LopId");

                    b.ToTable("essay_question_lop_visibility", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.ExamResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Correct")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ExamSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAutoSubmitted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("exam_results", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExamResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExpectedDurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("QuestionIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("InProgress");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Kind", "Status");

                    b.ToTable("exam_sessions", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.ExamSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalPoolSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("exam_sets", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.ExamVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExamSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("Mcq");

                    b.Property<string>("MaDe")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ExamSetId");

                    b.ToTable("exam_versions", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.ExamVersionLopVisibility", b =>
                {
                    b.Property<Guid>("ExamVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExamVersionId", "LopId");

                    b.HasIndex("LopId");

                    b.ToTable("exam_version_lop_visibility", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.ExamVersionOralQuestion", b =>
                {
                    b.Property<Guid>("ExamVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OralQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("ExamVersionId", "OralQuestionId");

                    b.HasIndex("OralQuestionId");

                    b.ToTable("exam_version_oral_questions", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.ExamVersionQuestion", b =>
                {
                    b.Property<Guid>("ExamVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("ExamVersionId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("exam_version_questions", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.OralQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chapter")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("ExpectedAnswer")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Chapter");

                    b.ToTable("oral_questions", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.OralQuestionLopVisibility", b =>
                {
                    b.Property<Guid>("OralQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OralQuestionId", "LopId");

                    b.HasIndex("LopId");

                    b.ToTable("oral_question_lop_visibility", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.OralResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AiScore")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ExamSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FollowupAnswersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainAnswer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RubricScoresJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExamSessionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("oral_results", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.PracticeSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chapter")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GiaoVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.ToTable("practice_sets", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.PracticeSetLopVisibility", b =>
                {
                    b.Property<Guid>("PracticeSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PracticeSetId", "LopId");

                    b.HasIndex("LopId");

                    b.ToTable("practice_set_lop_visibility", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chapter")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsPublishedForPractice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("SourceMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Manual");

                    b.Property<string>("Topic")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Chapter");

                    b.HasIndex("Difficulty");

                    b.ToTable("questions", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.QuestionLopVisibility", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuestionId", "LopId");

                    b.HasIndex("LopId");

                    b.ToTable("question_lop_visibility", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.QuizResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chapter")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Correct")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("quiz_results", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.WrongAnswer", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastWrongAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("WrongCount")
                        .HasColumnType("int");

                    b.HasKey("UserId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("wrong_answers", "quiz");
                });

            modelBuilder.Entity("QuizService.Api.Entities.EssayQuestionLopVisibility", b =>
                {
                    b.HasOne("QuizService.Api.Entities.EssayQuestion", null)
                        .WithMany()
                        .HasForeignKey("EssayQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizService.Api.Entities.ExamVersion", b =>
                {
                    b.HasOne("QuizService.Api.Entities.ExamSet", null)
                        .WithMany()
                        .HasForeignKey("ExamSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizService.Api.Entities.ExamVersionLopVisibility", b =>
                {
                    b.HasOne("QuizService.Api.Entities.ExamVersion", null)
                        .WithMany()
                        .HasForeignKey("ExamVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizService.Api.Entities.ExamVersionOralQuestion", b =>
                {
                    b.HasOne("QuizService.Api.Entities.ExamVersion", null)
                        .WithMany()
                        .HasForeignKey("ExamVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizService.Api.Entities.OralQuestion", null)
                        .WithMany()
                        .HasForeignKey("OralQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizService.Api.Entities.ExamVersionQuestion", b =>
                {
                    b.HasOne("QuizService.Api.Entities.ExamVersion", null)
                        .WithMany()
                        .HasForeignKey("ExamVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizService.Api.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizService.Api.Entities.OralQuestionLopVisibility", b =>
                {
                    b.HasOne("QuizService.Api.Entities.OralQuestion", null)
                        .WithMany()
                        .HasForeignKey("OralQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizService.Api.Entities.OralResult", b =>
                {
                    b.HasOne("QuizService.Api.Entities.OralQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizService.Api.Entities.PracticeSetLopVisibility", b =>
                {
                    b.HasOne("QuizService.Api.Entities.PracticeSet", null)
                        .WithMany()
                        .HasForeignKey("PracticeSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizService.Api.Entities.QuestionLopVisibility", b =>
                {
                    b.HasOne("QuizService.Api.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizService.Api.Entities.WrongAnswer", b =>
                {
                    b.HasOne("QuizService.Api.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
