// <auto-generated />
using System;
using AdminService.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminService.Api.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20260819155236_AddLopDeletionAudit")]
    partial class AddLopDeletionAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("admin")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdminService.Api.Entities.LopDeletionAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityLogsCount")
                        .HasColumnType("int");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EssayQuestionVisibilityCount")
                        .HasColumnType("int");

                    b.Property<int>("ExamResultsCount")
                        .HasColumnType("int");

                    b.Property<int>("ExamSessionsCount")
                        .HasColumnType("int");

                    b.Property<int>("ExamVersionVisibilityCount")
                        .HasColumnType("int");

                    b.Property<Guid>("LopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LopTen")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("OralResultsCount")
                        .HasColumnType("int");

                    b.Property<Guid>("PreparationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PreparedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionVisibilityCount")
                        .HasColumnType("int");

                    b.Property<int>("QuizResultsCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StepResultsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentProgressCount")
                        .HasColumnType("int");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("int");

                    b.Property<int>("StudyLogsCount")
                        .HasColumnType("int");

                    b.Property<int>("WrongAnswersCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LopId");

                    b.HasIndex("PreparationId")
                        .IsUnique();

                    b.ToTable("lop_deletion_audits", "admin");
                });

            modelBuilder.Entity("AdminService.Api.Entities.RoleChangeAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("OldRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAtUtc");

                    b.ToTable("role_change_audits", "admin");
                });

            modelBuilder.Entity("AdminService.Api.Entities.SystemConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Key");

                    b.ToTable("system_configs", "admin");
                });
#pragma warning restore 612, 618
        }
    }
}
